/**
* @File Name : test.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : August 12, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | August 12, 2024 |   | Initial Version
**/

public class test {
	@AuraEnabled
	Public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}